"""I'm creating all the tables

Revision ID: 6e933bbe8599
Revises: cc9ff63a884c
Create Date: 2026-05-06 15:02:55.645320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e933bbe8599'
down_revision = 'cc9ff63a884c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('business_email', sa.String(), nullable=False),
    sa.Column('business_address', sa.String(), nullable=False),
    sa.Column('business_phone', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('bank_code', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('contract_statements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('escrow_id', sa.String(), nullable=False),
    sa.Column('statement_text', sa.Text(), nullable=False),
    sa.Column('is_fulfilled', sa.Boolean(), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(), nullable=True),
    sa.Column('required_confirmation_from', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['escrow_id'], ['escrows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('dispute', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('escrows', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.drop_constraint(batch_op.f('escrows_seller_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'vendors', ['seller_id'], ['id'])

    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.drop_column('rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('phone')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('escrows', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('escrows_seller_id_fkey'), 'users', ['seller_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('dispute', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('contract_statements')
    op.drop_table('vendors')
    # ### end Alembic commands ###
